#[derive(Debug, Clone)]
pub enum Bathroom {
    SharedOnHall,
    PerRoom,
}

#[derive(Debug)]
#[allow(clippy::upper_case_acronyms)]
pub enum Community {
    FE,
    Explore,
    GrandChallenges,
    TYE,
    FYSA,
    GlobalLeadership,
}

#[derive(Debug, Clone)]
pub enum Location {
    WestCampus,
    EastCampus,
}

#[derive(Debug)]
pub enum RoomStyle {
    Doubles,
    Triples,
    Quad,
    Suite,
}

#[derive(Debug, Clone)]
pub enum Laundry {
    OtherBuilding,
    OneFloor,
    EveryFloor,
}

#[derive(Debug, Clone)]
pub struct Hall {
    pub name: &'static str,
    pub bathroom: Bathroom,
    pub communities: &'static [Community],
    pub location: Location,
    pub room_styles: &'static [RoomStyle],
    pub coed: bool,
    pub elevator: bool,
    pub laundry: Laundry,
    pub built: i32,                        // year
    pub last_renovated: i32,               // year
    pub room_area: i32,                    // square inches
    pub time_to_brittain: i32,             // minutes
    pub time_to_student_center: i32,       // minutes
    pub time_to_college_of_computing: i32, // minutes
    pub time_to_crc: i32,                  // minutes
    pub time_to_library: i32,              // minutes
}

pub fn get_housing() -> Vec<Hall> {
    vec![
        Hall {
            name: "Armstrong",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: true,
            laundry: Laundry::OtherBuilding,
            built: 1969,
            last_renovated: 2006,
            room_area: 24920,
            time_to_brittain: 23,
            time_to_student_center: 13,
            time_to_college_of_computing: 10,
            time_to_crc: 8,
            time_to_library: 14,
        },
        Hall {
            name: "Brown",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1925,
            last_renovated: 1993,
            room_area: 21600,
            time_to_brittain: 2,
            time_to_student_center: 11,
            time_to_college_of_computing: 14,
            time_to_crc: 17,
            time_to_library: 7,
        },
        Hall {
            name: "Caldwell",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE, Community::Explore],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1969,
            last_renovated: 2002,
            room_area: 21600,
            time_to_brittain: 23,
            time_to_student_center: 14,
            time_to_college_of_computing: 10,
            time_to_crc: 8,
            time_to_library: 14,
        },
        Hall {
            name: "Cloudman",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE, Community::GrandChallenges],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles, RoomStyle::Triples],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1931,
            last_renovated: 1995,
            room_area: 21600,
            time_to_brittain: 2,
            time_to_student_center: 12,
            time_to_college_of_computing: 13,
            time_to_crc: 17,
            time_to_library: 6,
        },
        Hall {
            name: "Field",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles, RoomStyle::Quad],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1961,
            last_renovated: 2005,
            room_area: 23760,
            time_to_brittain: 3,
            time_to_student_center: 10,
            time_to_college_of_computing: 12,
            time_to_crc: 16,
            time_to_library: 4,
        },
        Hall {
            name: "Fitten",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: true,
            laundry: Laundry::OneFloor,
            built: 1972,
            last_renovated: 2012,
            room_area: 26410,
            time_to_brittain: 22,
            time_to_student_center: 12,
            time_to_college_of_computing: 9,
            time_to_crc: 7,
            time_to_library: 13,
        },
        Hall {
            name: "Folk",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE, Community::Explore],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1969,
            last_renovated: 2005,
            room_area: 25576,
            time_to_brittain: 23,
            time_to_student_center: 14,
            time_to_college_of_computing: 10,
            time_to_crc: 8,
            time_to_library: 14,
        },
        Hall {
            name: "Freeman",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: true,
            laundry: Laundry::OtherBuilding,
            built: 1972,
            last_renovated: 2011,
            room_area: 27160,
            time_to_brittain: 21,
            time_to_student_center: 11,
            time_to_college_of_computing: 9,
            time_to_crc: 6,
            time_to_library: 12,
        },
        Hall {
            name: "Glenn",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles, RoomStyle::Triples, RoomStyle::Quad],
            coed: true,
            elevator: true,
            laundry: Laundry::EveryFloor,
            built: 1947,
            last_renovated: 2015,
            room_area: 23808,
            time_to_brittain: 3,
            time_to_student_center: 11,
            time_to_college_of_computing: 12,
            time_to_crc: 16,
            time_to_library: 5,
        },
        Hall {
            name: "Hanson",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1961,
            last_renovated: 2002,
            room_area: 24156,
            time_to_brittain: 3,
            time_to_student_center: 11,
            time_to_college_of_computing: 12,
            time_to_crc: 16,
            time_to_library: 5,
        },
        Hall {
            name: "Harris",
            bathroom: Bathroom::PerRoom,
            communities: &[Community::FE, Community::TYE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Suite],
            coed: true,
            elevator: true,
            laundry: Laundry::OtherBuilding,
            built: 1926,
            last_renovated: 1992,
            room_area: 25920,
            time_to_brittain: 2,
            time_to_student_center: 11,
            time_to_college_of_computing: 14,
            time_to_crc: 17,
            time_to_library: 7,
        },
        Hall {
            name: "Harrison",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles, RoomStyle::Quad],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1939,
            last_renovated: 1998,
            room_area: 24156,
            time_to_brittain: 1,
            time_to_student_center: 13,
            time_to_college_of_computing: 14,
            time_to_crc: 18,
            time_to_library: 7,
        },
        Hall {
            name: "Hefner",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: true,
            laundry: Laundry::OtherBuilding,
            built: 1969,
            last_renovated: 2008,
            room_area: 24920,
            time_to_brittain: 22,
            time_to_student_center: 13,
            time_to_college_of_computing: 9,
            time_to_crc: 8,
            time_to_library: 13,
        },
        Hall {
            name: "Hopkins",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles, RoomStyle::Quad],
            coed: true,
            elevator: false,
            laundry: Laundry::OneFloor,
            built: 1961,
            last_renovated: 1995,
            room_area: 24120,
            time_to_brittain: 3,
            time_to_student_center: 11,
            time_to_college_of_computing: 12,
            time_to_crc: 16,
            time_to_library: 5,
        },
        Hall {
            name: "Howell",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE, Community::GrandChallenges],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles, RoomStyle::Quad],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1939,
            last_renovated: 1999,
            room_area: 23808,
            time_to_brittain: 1,
            time_to_student_center: 13,
            time_to_college_of_computing: 15,
            time_to_crc: 19,
            time_to_library: 7,
        },
        Hall {
            name: "Matheson",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FYSA, Community::FE, Community::GlobalLeadership],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1961,
            last_renovated: 2002,
            room_area: 24120,
            time_to_brittain: 3,
            time_to_student_center: 11,
            time_to_college_of_computing: 11,
            time_to_crc: 16,
            time_to_library: 5,
        },
        Hall {
            name: "Montag",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: true,
            laundry: Laundry::OtherBuilding,
            built: 1972,
            last_renovated: 2011,
            room_area: 27160,
            time_to_brittain: 21,
            time_to_student_center: 11,
            time_to_college_of_computing: 10,
            time_to_crc: 6,
            time_to_library: 12,
        },
        Hall {
            name: "Perry",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FYSA, Community::FE, Community::GlobalLeadership],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles],
            coed: true,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1961,
            last_renovated: 2002,
            room_area: 23040,
            time_to_brittain: 3,
            time_to_student_center: 11,
            time_to_college_of_computing: 11,
            time_to_crc: 16,
            time_to_library: 5,
        },
        Hall {
            name: "Smith",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles, RoomStyle::Quad],
            coed: false,
            elevator: false,
            laundry: Laundry::OtherBuilding,
            built: 1947,
            last_renovated: 1993,
            room_area: 23736,
            time_to_brittain: 1,
            time_to_student_center: 10,
            time_to_college_of_computing: 14,
            time_to_crc: 17,
            time_to_library: 7,
        },
        Hall {
            name: "Towers",
            bathroom: Bathroom::SharedOnHall,
            communities: &[Community::FE],
            location: Location::EastCampus,
            room_styles: &[RoomStyle::Doubles, RoomStyle::Triples, RoomStyle::Quad],
            coed: true,
            elevator: true,
            laundry: Laundry::EveryFloor,
            built: 1947,
            last_renovated: 2014,
            room_area: 23994,
            time_to_brittain: 2,
            time_to_student_center: 11,
            time_to_college_of_computing: 12,
            time_to_crc: 16,
            time_to_library: 5,
        },
        Hall {
            name: "Woodruff North",
            bathroom: Bathroom::PerRoom,
            communities: &[Community::FE],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Suite],
            coed: true,
            elevator: true,
            laundry: Laundry::OtherBuilding,
            built: 1984,
            last_renovated: 2020,
            room_area: 27360,
            time_to_brittain: 24,
            time_to_student_center: 15,
            time_to_college_of_computing: 12,
            time_to_crc: 8,
            time_to_library: 15,
        },
        Hall {
            name: "Woodruff South",
            bathroom: Bathroom::PerRoom,
            communities: &[Community::FE],
            location: Location::WestCampus,
            room_styles: &[RoomStyle::Suite],
            coed: true,
            elevator: true,
            laundry: Laundry::OneFloor,
            built: 1984,
            last_renovated: 2020,
            room_area: 27360,
            time_to_brittain: 24,
            time_to_student_center: 15,
            time_to_college_of_computing: 12,
            time_to_crc: 8,
            time_to_library: 15,
        },
    ]
}
